### ISSUE TITLE
commit part file

### ISSUE THREAD

**Issue by linkai0001** [centic9/jgit-cookbook#72]
Hello, what is the api method of commit part of the file?

**Comment by centic9** [comment]
It does not look like JGit actually support this as far as I see, it will likely require going deep into the JGit implementation via DirCacheBuilder or other low-level classes, however people on Stackoverflow might know better than me.

An alternative approach will be to create a temporary backup of the file and adjust it so that it has only the changes to commit and after adding/committing it, restoring the backup of the file again.

In general please stick to the note that we defined for this repository: 

*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*

**Comment by linkai0001** [comment]
Hello, borrowing from the test case of jgit, setOnly in CommitCommand provides this function, and it is provided to similar people who encounter this problem.
usage:
try (Git git = this.getGit ()) {
     git.commit (). setOnly ("filename"). setMessage ("Only submit filename files"). call ();
}
